apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-eventhub
  namespace: ns-posthub--env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-eventhub
  template:
    metadata:
      labels:
        app: nats-eventhub
    spec:
      containers:
      - name: nats-eventhub
        image: nats-streaming:0.24.0
        args: [
          '-p',
          '4222',
          '-m',
          '8222',
          '-hbi',
          '5s',
          '-hbf',
          '2',
          '-SD',
          '-cid',
          'posthubcluster',
        ]
        # resources:
        #   limits:
        #     memory: "1128Mi"
        #     # cpu: "3000m"
        #     cpu: "500m"


---
kind: Service
apiVersion: v1
metadata:
  name:  nats-eventhub-service
  namespace: ns-posthub--env
spec:
  selector:
    app:  nats-eventhub
  type:  ClusterIP
  ports:
  - name:  client
    port:  4222
    targetPort:  4222
    protocol: TCP
  - name:  monitoring
    port:  8222
    targetPort:  8222
    protocol: TCP


